### ISSUE TITLE
the ids are unfortunately not clear.

### ISSUE THREAD

**Issue by HalloWelt42** [rozek/locally-unique-id-generator#1]
i have tested the script. unfortunately it is not suitable to generate unique id. as soon as you load the page, all id are generated again. it may be that it seems almost logical, but it is not made clear to the user.

I have apps that use localeStorage and there the uniqueness is mandatory.

**Comment by rozek** [comment]
Good point.

If you need completely unique ids, I'd recommend to use UUIDs/GUIDs. Here is a possibility how to generate them (if cryptographic uniqueness is not required):

```
/**** newUUID ****/

  function newUUID ():string {
    let Id = '', IdPart
    IdPart = Math.round(Math.random()*0xffffffff).toString(16)
      Id += IdPart + '00000000'.slice(IdPart.length) + '-'
      IdPart = Math.round(Math.random()*0xffff).toString(16)
      Id += IdPart + '0000'.slice(IdPart.length) + '-4'
      IdPart = Math.round(Math.random()*0xfff).toString(16)
      Id += IdPart + '000'.slice(IdPart.length) + '-'
      IdPart = Math.round(Math.random()*0x3fff+0x8000).toString(16)
      Id += IdPart + '-'
      IdPart = Math.round(Math.random()*0xffffffffffff).toString(16)
      Id += IdPart + '000000000000'.slice(IdPart.length)
    return Id.toLowerCase()
  }
```

**Comment by rozek** [comment]
I've updated the docs and included the above example
